version: "3.8"

services:
  vite:
    image: node:20-alpine
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
