/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The JSON representation used for import and export of KMs uses packages (event containers) bundled in a single object.
 */
export type PackageBundle = PackageBundleObject;
/**
 * ID of organization
 */
export type OrganizationID = string;
/**
 * ID of knowledge model
 */
export type KnowledgeModelID = string;
/**
 * Simple semantic version tag, e.g., ``1.0.45``
 */
export type SemVer = string;
/**
 * Unique composed ID for a package
 */
export type PackageID = string;
/**
 * Standard ISO timestamp format, e.g., ``2019-06-09T14:25:58.438Z``
 */
export type Timestamp = string;
/**
 * An event represents a single change in a KM. There are events for each entity type and usually three types of changes: **Add**, **Edit**, and **Delete**. In some cases, also **Move** event is possible.
 */
export type Event =
  | AddKnowledgeModelEvent
  | EditKnowledgeModelEvent
  | AddChapterEvent
  | EditChapterEvent
  | DeleteChapterEvent
  | AddOptionsQuestionEvent
  | AddListQuestionEvent
  | AddItemSelectQuestionEvent
  | AddValueQuestionEvent
  | AddIntegrationQuestionEvent
  | AddMultiChoiceQuestionEvent
  | AddFileQuestionEvent
  | EditOptionsQuestionEvent
  | EditListQuestionEvent
  | EditItemSelectQuestionEvent
  | EditValueQuestionEvent
  | EditIntegrationQuestionEvent
  | EditMultiChoiceQuestionEvent
  | EditFileQuestionEvent
  | DeleteQuestionEvent
  | AddAnswerEvent
  | EditAnswerEvent
  | DeleteAnswerEvent
  | AddExpertEvent
  | EditExpertEvent
  | DeleteExpertEvent
  | AddResourcePageReferenceEvent
  | AddURLReferenceEvent
  | AddCrossReferenceEvent
  | EditResourcePageReferenceEvent
  | EditURLReferenceEvent
  | EditCrossReferenceEvent
  | DeleteReferenceEvent
  | AddTagEvent
  | EditTagEvent
  | DeleteTagEvent
  | AddAPIIntegrationEvent
  | AddIntegrationEvent
  | EditIntegrationEvent
  | EditIntegrationEvent1
  | DeleteIntegrationEvent
  | MoveQuestionEvent
  | MoveAnswerEvent
  | MoveExpertEvent
  | MoveReferenceEvent
  | AddChoiceEvent
  | EditChoiceEvent
  | DeleteChoiceEvent
  | AddMetricEvent
  | EditMetricEvent
  | DeleteMetricEvent
  | AddPhaseEvent
  | EditPhaseEvent
  | DeletePhaseEvent
  | AddResourceCollectionEvent
  | EditResourceCollectionEvent
  | DeleteResourceCollectionEvent
  | AddResourcePageEvent
  | EditResourcePageEvent
  | DeleteResourcePageEvent;
/**
 * UUID version 4 according to `RFC4122 <https://tools.ietf.org/html/rfc4122>`_
 */
export type UUID = string;
export type ListOfKeyValuePairs = KeyValuePair[];
export type OptionalString = string | null;
/**
 * Indicates if a question is desirable in certain phase of a project
 */
export type DesirabilityPhase = UUID | null;
export type ValueType =
  | "StringQuestionValueType"
  | "NumberQuestionValueType"
  | "DateQuestionValueType"
  | "DateTimeQuestionValueType"
  | "TimeQuestionValueType"
  | "TextQuestionValueType"
  | "EmailQuestionValueType"
  | "UrlQuestionValueType"
  | "ColorQuestionValueType";
export type OptionalInteger = number | null;

/**
 * Collection of potentially multiple linked Knowledge Model packages that is commonly used for import and export in DSW.
 */
export interface PackageBundleObject {
  metamodelVersion: number;
  name: string;
  organizationId: OrganizationID;
  kmId: KnowledgeModelID;
  version: SemVer;
  id: PackageID;
  packages: Package[];
  [k: string]: unknown;
}
/**
 * A single KM package that holds changes (or more precisely events) for the specific version.
 */
export interface Package {
  metamodelVersion?: number;
  name?: string;
  organizationId?: OrganizationID;
  kmId?: KnowledgeModelID;
  version?: SemVer;
  id?: PackageID;
  description?: string;
  readme?: string;
  license?: string;
  forkOfPackageId?: PackageID;
  mergeCheckpointPackageId?: PackageID;
  previousPackageId?: PackageID;
  createdAt?: Timestamp;
  events?: Event[];
  [k: string]: unknown;
}
/**
 * Add a new Knowledge Model (typically only once and the very first event) as the top-level entity
 */
export interface AddKnowledgeModelEvent {
  eventType: "AddKnowledgeModelEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  annotations: ListOfKeyValuePairs;
}
export interface KeyValuePair {
  key?: string;
  value?: string;
  [k: string]: unknown;
}
/**
 * Edit properties of the top-level entity
 */
export interface EditKnowledgeModelEvent {
  eventType: "EditKnowledgeModelEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  chapterUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  tagUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  integrationUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  metricUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  phaseUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  resourcePageCollectionUuids?: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Add a new chapter to the KM
 */
export interface AddChapterEvent {
  eventType: "AddChapterEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: string;
  text: OptionalString;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing chapter in the KM
 */
export interface EditChapterEvent {
  eventType: "EditChapterEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  questionUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing chapter from the KM
 */
export interface DeleteChapterEvent {
  eventType: "DeleteChapterEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new options question to the KM
 */
export interface AddOptionsQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "OptionsQuestion";
  title: string;
  text: OptionalString;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new list question to the KM
 */
export interface AddListQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "ListQuestion";
  title: string;
  text: OptionalString;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new item select question to the KM
 */
export interface AddItemSelectQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  listQuestionUuid: UUID;
  createdAt: string;
  questionType: "ListQuestion";
  title: string;
  text: OptionalString;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new value question to the KM
 */
export interface AddValueQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "ValueQuestion";
  title: string;
  text: OptionalString;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  valueType: ValueType;
  validations: QuestionValidation[];
  annotations: ListOfKeyValuePairs;
}
export interface QuestionValidation {
  type:
    | "MinLengthQuestionValidation"
    | "MaxLengthQuestionValidation"
    | "RegexQuestionValidation"
    | "OrcidQuestionValidation"
    | "DoiQuestionValidation"
    | "MinNumberQuestionValidation"
    | "MaxNumberQuestionValidation"
    | "FromDateQuestionValidation"
    | "ToDateQuestionValidation"
    | "FromDateTimeQuestionValidation"
    | "ToDateTimeQuestionValidation"
    | "FromTimeQuestionValidation"
    | "ToTimeQuestionValidation"
    | "DomainQuestionValidation";
  value?: number | string;
}
/**
 * Add a new integration question to the KM
 */
export interface AddIntegrationQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "IntegrationQuestion";
  title: string;
  text: OptionalString;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  integrationUuid: UUID;
  props: StringMap;
  annotations: ListOfKeyValuePairs;
}
/**
 * Representation of simple map where both keys and values are strings
 */
export interface StringMap {
  /**
   * This interface was referenced by `StringMap`'s JSON-Schema definition
   * via the `patternProperty` ".*".
   */
  [k: string]: string;
}
/**
 * Add a new multi-choice question to the KM
 */
export interface AddMultiChoiceQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "MultiChoiceQuestion";
  title: string;
  text: OptionalString;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new file question to the KM
 */
export interface AddFileQuestionEvent {
  eventType: "AddQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "FileQuestion";
  title: string;
  text: OptionalString;
  fileTypes: OptionalString;
  maxSize: OptionalInteger;
  requiredPhaseUuid: DesirabilityPhase;
  tagUuids: UUID[];
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing options question in the KM
 */
export interface EditOptionsQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "OptionsQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  answerUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing list question in the KM
 */
export interface EditListQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "ListQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids?: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  itemTemplateQuestionUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing list question in the KM
 */
export interface EditItemSelectQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "ItemSelectQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids?: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  listQuestionUuid: {
    changed: boolean;
    value?: UUID;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing value question in the KM
 */
export interface EditValueQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "ValueQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  validations: {
    changed: boolean;
    value?: QuestionValidation[];
    [k: string]: unknown;
  };
  valueType: {
    changed: boolean;
    value?: ValueType;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing integration question in the KM
 */
export interface EditIntegrationQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "IntegrationQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  integrationUuid: {
    changed: boolean;
    value?: UUID;
    [k: string]: unknown;
  };
  props: {
    changed: boolean;
    value?: StringMap;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing multi-choice question in the KM
 */
export interface EditMultiChoiceQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "MultiChoiceQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  choiceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing file question in the KM
 */
export interface EditFileQuestionEvent {
  eventType: "EditQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  questionType: "FileQuestion";
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  text: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  fileTypes: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  maxSize: {
    changed: boolean;
    value?: OptionalInteger;
    [k: string]: unknown;
  };
  requiredPhaseUuid: {
    changed: boolean;
    value?: DesirabilityPhase;
    [k: string]: unknown;
  };
  tagUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  expertUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  referenceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  choiceUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing question from the KM
 */
export interface DeleteQuestionEvent {
  eventType: "DeleteQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new answer to the KM
 */
export interface AddAnswerEvent {
  eventType: "AddAnswerEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  label: string;
  advice: OptionalString;
  metricMeasures: MetricMeasure[];
  annotations: ListOfKeyValuePairs;
}
/**
 * Entity capturing how certain metric is affected
 */
export interface MetricMeasure {
  metricUuid: UUID;
  measure: number;
  weight: number;
}
/**
 * Edit an existing answer in the KM
 */
export interface EditAnswerEvent {
  eventType: "EditAnswerEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  label: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  advice: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  followUpUuids: {
    changed: boolean;
    value?: UUID;
    [k: string]: unknown;
  };
  metricMeasures: {
    changed: boolean;
    value?: MetricMeasure;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing answer from the KM
 */
export interface DeleteAnswerEvent {
  eventType: "DeleteAnswerEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new expert to the KM
 */
export interface AddExpertEvent {
  eventType: "AddExpertEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  name: string;
  email: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing expert in the KM
 */
export interface EditExpertEvent {
  eventType: "EditExpertEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  name: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  email: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing expert from the KM
 */
export interface DeleteExpertEvent {
  eventType: "DeleteExpertEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new resource page reference to the KM
 */
export interface AddResourcePageReferenceEvent {
  eventType: "AddReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  referenceType?: "ResourcePageReference";
  shortUuid: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new URL reference to the KM
 */
export interface AddURLReferenceEvent {
  eventType: "AddReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  referenceType?: "URLReference";
  url: string;
  label: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new cross-reference to the KM
 */
export interface AddCrossReferenceEvent {
  eventType: "AddReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  referenceType: "CrossReference";
  targetUuid: string;
  description: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing resource page reference in the KM
 */
export interface EditResourcePageReferenceEvent {
  eventType: "EditReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  referenceType: "ResourcePageReference";
  shortUuid: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing URL reference in the KM
 */
export interface EditURLReferenceEvent {
  eventType: "EditReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  referenceType: "URLReference";
  url: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  label: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing cross-reference in the KM
 */
export interface EditCrossReferenceEvent {
  eventType: "EditReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  referenceType: "CrossReference";
  targetUuid: {
    changed: boolean;
    value?: UUID;
    [k: string]: unknown;
  };
  description: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing reference from the KM
 */
export interface DeleteReferenceEvent {
  eventType: "DeleteReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new tag to the KM
 */
export interface AddTagEvent {
  eventType: "AddTagEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  name: string;
  description: OptionalString;
  color: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing tag in the KM
 */
export interface EditTagEvent {
  eventType: "EditTagEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  name: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  description: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  color: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing tag from the KM
 */
export interface DeleteTagEvent {
  eventType: "DeleteTagEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new integration to the KM
 */
export interface AddAPIIntegrationEvent {
  eventType: "AddIntegrationEvent";
  integrationType?: "ApiIntegration";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  id: string;
  name: string;
  logo: OptionalString;
  props: string[];
  itemUrl: OptionalString;
  requestMethod: string;
  requestUrl: string;
  requestHeaders: ListOfKeyValuePairs;
  requestBody: string;
  requestEmptySearch: boolean;
  responseItemId?: OptionalString;
  responseItemTemplate?: string;
  responseListField: OptionalString;
  annotations: ListOfKeyValuePairs;
}
/**
 * Add a new integration to the KM
 */
export interface AddIntegrationEvent {
  eventType: "AddIntegrationEvent";
  integrationType?: "WidgetIntegration";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  id: string;
  name: string;
  logo: string;
  props: string[];
  itemUrl: string;
  widgetUrl: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing integration entity
 */
export interface EditIntegrationEvent {
  eventType: "EditIntegrationEvent";
  integrationType?: "ApiIntegration";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  id: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  name: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  logo: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  props: {
    changed: boolean;
    value?: string[];
    [k: string]: unknown;
  };
  requestMethod: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  requestUrl: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  requestHeaders: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
  requestBody: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  requestEmptySearch: {
    changed: boolean;
    value?: boolean;
    [k: string]: unknown;
  };
  responseItemId?: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  responseItemTemplate?: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  itemUrl: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  responseListField: {
    changed: boolean;
    value?: OptionalString;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Edit an existing integration entity
 */
export interface EditIntegrationEvent1 {
  eventType: "EditIntegrationEvent";
  integrationType?: "WidgetIntegration";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  id: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  name: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  logo: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  props: {
    changed: boolean;
    value?: string[];
    [k: string]: unknown;
  };
  itemUrl: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  widgetUrl: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing integration from the KM
 */
export interface DeleteIntegrationEvent {
  eventType: "DeleteIntegrationEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Move an existing question to a different location in the KM
 */
export interface MoveQuestionEvent {
  eventType: "MoveQuestionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  targetUuid: UUID;
}
/**
 * Move an existing answer to a different location in the KM
 */
export interface MoveAnswerEvent {
  eventType: "MoveAnswerEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  targetUuid: UUID;
}
/**
 * Move an existing expert to a different location in the KM
 */
export interface MoveExpertEvent {
  eventType: "MoveExpertEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  targetUuid: UUID;
}
/**
 * Move an existing reference to a different location in the KM
 */
export interface MoveReferenceEvent {
  eventType: "MoveReferenceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  targetUuid: UUID;
}
/**
 * Add a new choice to the KM
 */
export interface AddChoiceEvent {
  eventType: "AddChoiceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  label: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing choice in the KM
 */
export interface EditChoiceEvent {
  eventType: "EditChoiceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  label: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing choice from the KM
 */
export interface DeleteChoiceEvent {
  eventType: "DeleteChoiceEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new metric to the KM
 */
export interface AddMetricEvent {
  eventType: "AddMetricEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: string;
  abbreviation: string;
  description: OptionalString;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing metric in the KM
 */
export interface EditMetricEvent {
  eventType: "EditMetricEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  abbreviation: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  description: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing metric from the KM
 */
export interface DeleteMetricEvent {
  eventType: "DeleteMetricEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new phase to the KM
 */
export interface AddPhaseEvent {
  eventType: "AddPhaseEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: string;
  description: OptionalString;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing phase in the KM
 */
export interface EditPhaseEvent {
  eventType: "EditPhaseEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  description: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing phase from the KM
 */
export interface DeletePhaseEvent {
  eventType: "DeletePhaseEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new resource collection to the KM
 */
export interface AddResourceCollectionEvent {
  eventType: "AddResourceCollectionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing resource collection in the KM
 */
export interface EditResourceCollectionEvent {
  eventType: "EditResourceCollectionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  resourcePageUuids: {
    changed: boolean;
    value?: UUID[];
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing resource collection from the KM
 */
export interface DeleteResourceCollectionEvent {
  eventType: "DeleteResourceCollectionEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
/**
 * Add a new resource page to the KM
 */
export interface AddResourcePageEvent {
  eventType: "AddResourcePageEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: string;
  content: string;
  annotations: ListOfKeyValuePairs;
}
/**
 * Edit an existing resource page in the KM
 */
export interface EditResourcePageEvent {
  eventType: "EditResourcePageEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
  title: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  content: {
    changed: boolean;
    value?: string;
    [k: string]: unknown;
  };
  annotations: {
    changed: boolean;
    value?: ListOfKeyValuePairs;
    [k: string]: unknown;
  };
}
/**
 * Delete an existing resource page from the KM
 */
export interface DeleteResourcePageEvent {
  eventType: "DeleteResourcePageEvent";
  uuid: UUID;
  parentUuid: UUID;
  entityUuid: UUID;
  createdAt: string;
}
